# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BubbleBlastSaga' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BubbleBlastSaga
  pod 'PhysicsEngine', :git => 'https://edmundmok@bitbucket.org/cs3217/2017-ps4-a0093960x.git', :tag => '0.1.5'

  target 'BubbleBlastSagaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BubbleBlastSagaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
